### ISSUE TITLE
Zero weights in flow zone tables

### ISSUE THREAD

**Issue by jlehtoma** [VUEG/bdes_to#8]
Air quality, floodregulation and pollination all have 0 weights in the table (n=556 all together). Is this intentional?

**Comment by wverhagen** [comment]
yes you mean that some flow zones have zero weights.
that is intentional. these are actually areas with either no ES or only cells with zero value for that service.
we could filter those out based on the table, potentially. it however was a pain to filter those out prior to doing the cutting into zones.
but it is not necessary I believe.
willem

**Comment by jlehtoma** [comment]
Good, just wanted to check.
